### ISSUE TITLE
Conditions for macro injection could be more flexible

### ISSUE THREAD

**Issue by JayFoxRox** [jarikomppa/interjector#4]
It would be nice if the macros could be configured using simple boolean flags for conditions:

- Add macro on entry (top level "{")
- Add macro for explicit return ("return" at function level)
- Add macro for explicit return which might be conditional ("return" outside function level)
- Add macro for implicit exit (top level "}")
- Add macro for keywords like `if`, `for`, `while`, `goto`, `default`, or `case` (generally anything that branches)
- Add macro per-statement (full-tracing basically)
- ...

I'm also running on a platform like yours (no debugger), and also our compiler doesn't have a code-coverage plugin for our platform (which is essentially what your tool does).
If this tool was more flexible this could become very popular (or does something like this already exist?).

**Comment by jarikomppa** [comment]
I guess those could be added. My fear is that the usability may be reduced due to the fact that augmented code tends to get quite slow, but since it's up to the user to implement what those macros actually do... it might be useful.

**Comment by jarikomppa** [comment]
Lots of this would require way more robust parsing than what exists now, and while that would be a fun project, I'm not willing to put time into it (as of now, anyway). I did add an optional macro for leaving, which also gives the code block level. While doing all this I realized interjector was parsing code inside comments, which is.. bad.. so that should be fixed too now.
